name = "TensorCast"
uuid = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
authors = ["Michael Abbott"]
version = "0.2.1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LazyStack = "1fad7336-0346-5a1a-a56f-a06ba010965b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
Compat = "2.2, 3"
LazyArrays = "0.12, 0.13, 0.14, 0.15"
LazyStack = "0.0.4, 0.0.5, 0.0.6"
MacroTools = "0.5"
OffsetArrays = "0.11, 1.0"
StaticArrays = "0.10, 0.11, 0.12"
ZygoteRules = "0.1, 0.2"
julia = "1"

[extras]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Compat", "Einsum", "JuliennedArrays", "LoopVectorization", "Statistics", "Strided"]
