name = "TensorCast"
uuid = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
authors = ["Michael Abbott"]
version = "0.4.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LazyStack = "1fad7336-0346-5a1a-a56f-a06ba010965b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TransmuteDims = "24ddb15e-299a-5cc3-8414-dbddc482d9ca"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
Compat = "2.2, 3"
LazyStack = "0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8"
MacroTools = "0.5"
OffsetArrays = "0.11, 1.0"
Requires = "0.5, 1"
StaticArrays = "0.10, 0.11, 0.12, 1.0"
TransmuteDims = "0.1.7"
ZygoteRules = "0.2"
julia = "1.3"

[extras]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
JuliennedArrays = "5cadff95-7770-533d-a838-a1bf817ee6e0"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Compat", "Einsum", "JuliennedArrays", "LazyArrays", "LoopVectorization", "OffsetArrays", "Statistics", "Strided"]
